plugins {
    id("conventions.kmp.build-targets")
    id("extensions.project-globals")
}


/* Inject Build.isDebug constant, `true` if gradle.properties.debug=true. */
val isDebugBuild = project.hasProperty("debug")
        && project.properties["debug"]?.toString()?.lowercase() == "true"

val pkg = projectGlobals.projectPackage("core")
val generatedSrcDir =
    layout.buildDirectory.get().dir("generated/kmp/main/kotlin/${pkg.replace(".", "/")}")

val generateBuildConfig by tasks.registering(Sync::class) {
    description = "Generates a Kotlin file with build configuration."

    from(provider {
        val tempFile = File(temporaryDir, "Build.kt")
        tempFile.parentFile.mkdirs()

        val fileContent = """
            // This file is auto-generated by Gradle. Do not edit.
            package $pkg
            
            object Build {
                val isDebug: Boolean = $isDebugBuild
                val AppName: String = "${projectGlobals.projectNameUI}"
            }
        """.trimIndent()

        tempFile.writeText(fileContent)
        return@provider files(tempFile)
    })
    into(generatedSrcDir)
}


kotlin {
    compilerOptions {
        optIn.add("kotlin.time.ExperimentalTime")
    }

    sourceSets {
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(project(":test"))
        }

        val commonMain by getting {
            dependencies {
                implementation(libs.kotlinx.coroutinesCore)
                implementation(libs.kotlinx.datetime)
            }
            kotlin.srcDir(generateBuildConfig)
        }
    }
}
