import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinxSerialization)
}


/* Inject Build.isDebug constant, `true` if gradle.properties.debug=true. */
val isDebugBuild = project.hasProperty("debug")
        && project.properties["debug"]?.toString()?.lowercase() == "true"

val pkg = "org.beatonma.gclocks.core"
val generatedSrcDir =
    layout.buildDirectory.get().dir("generated/kmp/main/kotlin/${pkg.replace(".", "/")}")

val generateBuildConfig by tasks.registering(Sync::class) {
    description = "Generates a Kotlin file with build configuration."

    from(provider {
        val tempFile = File(temporaryDir, "Build.kt")
        tempFile.parentFile.mkdirs()

        val fileContent = """
            // This file is auto-generated by Gradle. Do not edit.
            package $pkg
            
            object Build {
                val isDebug: Boolean = $isDebugBuild
            }
        """.trimIndent()

        tempFile.writeText(fileContent)
        return@provider files(tempFile)
    })
    into(generatedSrcDir)
}


kotlin {
    compilerOptions {
        optIn.add("kotlin.time.ExperimentalTime")
    }

    jvm {}

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser {}
    }

    sourceSets {
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(project(":test"))
        }

        val commonMain by getting {
            dependencies {
                implementation(libs.kotlinx.datetime)
                implementation(libs.kotlinx.serialization.json)
            }
            kotlin.srcDir(generatedSrcDir)
        }
    }
}

tasks.named("compileKotlinJvm").configure {
    dependsOn(generateBuildConfig)
}
tasks.named("compileKotlinWasmJs").configure {
    dependsOn(generateBuildConfig)
}
